################################################################################
#
# cryptoauthlib
#
################################################################################

CRYPTOAUTHLIB_VERSION = v3.3.3
CRYPTOAUTHLIB_SITE_METHOD = git
CRYPTOAUTHLIB_SITE = git@github.com:MicrochipTech/cryptoauthlib.git
CRYPTOAUTHLIB_LICENSE = EPL-1.0 or BSD-3-Clause
CRYPTOAUTHLIB_LICENSE_FILES = license.txt
CRYPTOAUTHLIB_INSTALL_STAGING = YES
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_HAL_HID),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_HAL_KIT_HID=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_HAL_KIT_HID=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_HAL_I2C),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_HAL_I2C=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_HAL_I2C=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_HAL_KIT_UART),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_HAL_KIT_UART=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_HAL_KIT_UART=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_PKCS11),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_PKCS11=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_PKCS11=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_ATECC608),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_ATECC608_SUPPORT=ON
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_ATECC608A_SUPPORT=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_ATECC608_SUPPORT=OFF
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_ATECC608A_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_TFLEX),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_TFLEX_SUPPORT=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_TFLEX_SUPPORT=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_OPENSSL),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_OPENSSL=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_OPENSSL=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_ATCAB_FUNCTIONS),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_USE_ATCAB_FUNCTIONS=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_USE_ATCAB_FUNCTIONS=OFF
endif
ifeq ($(BR2_PACKAGE_CRYPTOAUTHLIB_DEBUG),y)
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_PRINTF=ON
else
CRYPTOAUTHLIB_CONF_OPTS += -DATCA_PRINTF=OFF
endif

define CRYPTOAUTHLIB_INSTALL_UDEV_RULES
	$(INSTALL) -D -m 644 $(@D)/lib/hal/90-cryptohid.rules \
	$(TARGET_DIR)/etc/udev/rules.d/90-cryptohid.rules
endef
CRYPTOAUTHLIB_POST_INSTALL_TARGET_HOOKS += CRYPTOAUTHLIB_INSTALL_UDEV_RULES


$(eval $(cmake-package))
